name: commat
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.7
  - pytorch-cuda=11.7
  - pytorch
  - tqdm
  - ca-certificates
  - openssl
  - pandas
  - ml-collections
  - tree
  - biopython
  - modelcif
  - pynvml
  - scipy
  - seaborn
  - pip
  - pip:
    - igfold=0.4.0
